### ISSUE TITLE
supabase postgres graphql

### ISSUE THREAD

**Issue by masapasa** [supabase-community/supabase-graphql-example#51]
Hi @dthyresson @n1ru4l @thorwebdev @kiwicopple @ardatan 
I have a problem setting up local postgres and also connecting to supabase. Would you be kind enough to hop on a call and give me some hint? I would be really grateful.
Best
apyakurel@gmail.com

**Comment by dthyresson** [comment]
Hi @masapasa the best place to get support from the Supabase community is through:

* GitHub issues forum: https://github.com/supabase/supabase/discussions
* Discord Community (which has lots of people to help like the SupaSquad https://supabase.com/supasquad): https://discord.com/invite/R7bSpeBSJE
* Supabase Support itself once your signed up 

By the way, it is much much easier to get with Supabase using their hosted Postgres service that installing locally, see:


([Supabase Cloud](https://app.supabase.com/): you don't need to deploy anything. We will manage and scale your infrastructure.

Rather than having to install Docker are run it all locally:

[Docker](https://supabase.com/docs/guides/self-hosting/docker): deploy to your own infrastructure.

**Comment by masapasa** [comment]
Thank you @dthyresson for the reply. I am trying the supabase postgres graphql integration. But I would also like to figure it locally for easier and quicker development.

I am getting following error in vercel:


18:51:17.523 | Cloning github.com/masapasa/supabase-graphql-example (Branch: masa, Commit: 68959f7)
-- | --
18:51:17.790 | Previous build cache not available
18:51:17.990 | Cloning completed: 466.814ms
18:51:18.088 | Running "vercel build"
18:51:18.553 | Vercel CLI 28.13.0
18:51:18.783 | Running "install" command: `yarn`...
18:51:19.081 | yarn install v1.22.17
18:51:19.150 | [1/4] Resolving packages...
18:51:19.399 | [2/4] Fetching packages...
18:51:35.095 | [3/4] Linking dependencies...
18:51:35.098 | warning "@graphql-codegen/cli > cosmiconfig-typescript-loader@4.0.0" has unmet peer dependency "@types/node@*".
18:51:35.099 | warning "@graphql-codegen/cli > cosmiconfig-typescript-loader@4.0.0" has unmet peer dependency "ts-node@>=10".
18:51:35.099 | warning "@graphql-codegen/cli > cosmiconfig-typescript-loader@4.0.0" has unmet peer dependency "typescript@>=3".
18:51:35.100 | warning "@graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
18:51:35.100 | warning "@graphql-codegen/cli > graphql-config > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
18:51:35.101 | warning "@graphql-codegen/gql-tag-operations-preset > @graphql-codegen/gql-tag-operations@1.5.0" has unmet peer dependency "graphql-tag@^2.0.0".
18:51:35.103 | warning "workspace-aggregator-dca8861d-f837-4897-9496-e84d751b6daf > app > @graphql-yoga/render-graphiql@2.13.12" has unmet peer dependency "@graphql-yoga/common@^2.12.12".
18:51:49.415 | [4/4] Building fresh packages...
18:51:49.872 | Done in 30.80s.
18:51:49.903 | Detected Next.js version: 12.3.1
18:51:49.903 | Running "yarn codegen && yarn workspace app build"
18:51:50.172 | yarn run v1.22.17
18:51:50.214 | error Command "codegen" not found.
18:51:50.214 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
18:51:50.232 | Error: Command "yarn codegen && yarn workspace app build" exited with 1
